---
title: "131_Lab1"
author: Immad Ali
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Example 1
```{r}
library(ISLR)
library(tidyverse)
library(tibble)

data("Auto")
Auto = as_tibble(Auto)

# Basic filter of one variable
filter(Auto, mpg == 15)

#Can specify multiple variables to filter by.
filter(Auto, mpg == 15, displacement > 350)
```


```{r}
#Using select function to select those variables

select(Auto, mpg, displacement)

#Can also select from column names as a sequence
select(Auto, mpg:weight)
```

First lab, we used the filter function and installed the tibble package. 


# Basics of Data Processing

```{r, eval = TRUE}
# install.packages("tidyverse")
# install.packages("tidymodels")
# install.packages("ISLR")

library(tidyverse)
library(tidymodels)
library(ISLR)
```

Selecting observations by their value :

```{r}
filtered_mpg <- mpg %>%
  filter(class == "compact" & manufacturer == "audi")
```


On our Own:

```{r}
install.packages("nycflights13")
library(nycflights13)


```

